# Server Configuration
server:
  port: 8080
  compression:
    enabled: true
    mime-types:
     - application/json
     - application/xml
     - text/xml
     - text/css
     - text/plain
  http2:
    enabled: true
  shutdown: graceful
management:
  health:
    probes:
      enabled: true




# PostgreSQL Database Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/productschema
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

  # JPA Configuration for PostgreSQL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    # create table when the application starts and delete it when it stops
    # hibernate.ddl-auto: create-drop

    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
